#A full bar is 20.
FoodAmount: 20
#Message for when the player hits below the FoodPercentage! Use & to add colors, &c = red, &b = aqua
YouNeedToEatMessage: "&cYou need to eat!"
#Will the message show up above the hotbar?
YouNeedToEatHotbar: true
#Will the message show up in the chat?
YouNeedToEatChat: false
#Enable both if you want both, disabling both will cause issues.
Slowness: true
#In percentage when the player will crouch.
AmountToCrouch: 5
#How much many food levels should be given to the player when they consume something,
#20 = full bar
#10 = half
#etc etc etc
Consumables:
  Potion: 5
  Pork: 3
  GrilledPorkchop: 8
  Potato: 2
  CookedPotato: 5
  Mutton: 2
  CookedMutton: 6
  Beef: 3
  CookedBeef: 8
  Bread: 5
  Carrot: 3
  Melon: 2
  GoldenApple: 4
  MushroomSoup: 6
  Apple: 4
  Fish: 2
  CookedFish: 5
  Cookie: 2
  PumpkinPie: 5
  Rabbit: 5
  CookedRabbit: 5
  Chicken: 2
  CookedChicken: 6
  RabbitStew: 10
